[project]
name = "beyond-fa-randomvector"
version = "0.1.0"
description = "BeyondFA challenge random vector"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "simpleitk>=2.4.1",
]
